version: '3.2'

services:
  localstack:
    container_name: awsverso
    image: localstack/localstack:latest
    hostname: localstack
    network_mode: bridge
    ports:
      - "4566:4566"
      - "4571:4571"
      - "8080:8080"
    environment:
      - AWS_ACCESS_KEY_ID=lstack
      - AWS_SECRET_ACCESS_KEY=lstack
      - AWS_DEFAULT_REGION=us-east-1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./.localstack:/tmp/localstack"
      - "./entrypoint.d:/docker-entrypoint-initaws.d"