AWSTemplateFormatVersion: "2010-09-09"

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "lstack-bucket-dev"
      LoggingConfiguration:
        DestinationBucketName: "lstack-bucket-logs"
        LogFilePrefix: "lstack-bucket-dev"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: IntelligentTieringTransition
            Status: Enabled
            Transitions:
              - TransitionInDays: 5
                StorageClass: INTELLIGENT_TIERING
